"use client";
import { useEffect, useState } from "react";
import { ArrowRight, Mail, Menu, X } from "lucide-react";
const CONTACT_EMAIL = "contact@sideristerra.com";
const NAV_ITEMS = [["About", "#about"], ["Technology", "#technology"], ["Pilots", "#pilots"], ["Team", "#team"], ["Contact", "#contact"]] as const;
const TEAM_MEMBERS = [
  { name: "Diego Vachon Galindo", role: "Co-Founder", bio: "Mathematics & Computer Science at McGill University. Focused on software, data, and the development of the Sideris Terra platform.", photoUrl: "/founder-1.jpg", linkedinUrl: "https://www.linkedin.com/in/diego-vachon-galindo-263b66234/" },
  { name: "Nassim Ameur", role: "Co-Founder", bio: "Mathematics & Computer Science at McGill University, with a minor in Economics. Focused on product development, technology, partnerships, and business strategy at Sideris Terra.", photoUrl: "/founder-2.jpg", linkedinUrl: "https://www.linkedin.com/in/ameurnassim/" },
];
const primaryButton = "inline-flex h-11 items-center justify-center gap-2 border border-primary bg-primary px-5 text-sm font-semibold text-primary-foreground transition-colors hover:bg-transparent hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-background";
const outlineButton = "inline-flex h-11 items-center justify-center gap-2 border border-white/25 bg-transparent px-5 text-sm font-medium text-white transition-colors hover:border-primary hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:ring-offset-background";
function Brand() { return <a href="#top" className="inline-flex items-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary" aria-label="Sideris Terra, back to top"><img src="/logo.png" alt="Sideris Terra" className="h-9 w-auto object-contain" /></a>; }
function Navigation() {
  const [open, setOpen] = useState(false);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") setOpen(false); }; document.addEventListener("keydown", close); return () => document.removeEventListener("keydown", close); }, []);
  return <><nav className="hidden items-center gap-7 md:flex" aria-label="Primary navigation">{NAV_ITEMS.map(([label, href]) => <a key={label} href={href} className="nav-link">{label}</a>)}<a href={`mailto:${CONTACT_EMAIL}`} className="nav-contact">Contact us</a></nav><button type="button" className="mobile-menu-button md:hidden" aria-expanded={open} aria-controls="mobile-navigation" aria-label={open ? "Close navigation" : "Open navigation"} onClick={() => setOpen((value) => !value)}>{open ? <X aria-hidden="true" /> : <Menu aria-hidden="true" />}</button>{open && <nav id="mobile-navigation" className="mobile-navigation md:hidden" aria-label="Mobile navigation">{NAV_ITEMS.map(([label, href]) => <a key={label} href={href} className="mobile-nav-link" onClick={() => setOpen(false)}>{label}</a>)}<a href={`mailto:${CONTACT_EMAIL}`} className="mobile-nav-link mobile-nav-contact" onClick={() => setOpen(false)}>Contact us <ArrowRight aria-hidden="true" /></a></nav>}</>;
}
export default function Home() {
  const emailHref = `mailto:${CONTACT_EMAIL}`;
  return <main id="top" className="min-h-screen overflow-hidden bg-background">
    <header className="site-header"><div className="site-width header-inner"><Brand /><Navigation /></div></header>
    <section className="hero-section"><div className="site-width hero-grid"><div className="hero-copy"><h1>See crop stress before it becomes a problem.</h1><p className="hero-lede">A parcel-level crop monitoring platform that brings satellite observations, weather, crop development, and soil water balance into one clearer view.</p></div><figure className="hero-image"><img src="/contoured-agricultural-landscape-stockcake.jpg" alt="Contoured agricultural fields seen from above" /><figcaption>Field conditions, read in context.</figcaption></figure></div></section>
    <section id="technology" className="content-section scroll-mt-20"><div className="site-width"><div className="section-intro"><div><h2>The platform</h2><p className="section-lede">Our prototype brings the signals together in a single parcel-level view, giving teams a more direct way to understand crop conditions over time.</p></div></div><figure className="prototype-figure"><img src="/prototype%20image.png" alt="Sideris Terra crop monitoring prototype" /><figcaption>Prototype interface / parcel-level crop monitoring</figcaption></figure></div></section>
    <section id="about" className="content-section content-section-tight scroll-mt-20"><div className="site-width split-section"><div><h2>Our approach</h2><hr /><p className="section-lede">Agricultural decisions are often based on information coming from separate sources. Sideris Terra is being developed to combine these signals into a single parcel-level view, making it easier to understand where crop stress may be developing and where attention may be needed.</p></div></div></section>
    <section id="pilots" className="pilot-section scroll-mt-20"><div className="site-width pilot-layout"><div><h2>We are looking for pilot partners.</h2><div className="pilot-copy"><p>We are seeking pilot projects with growers, agricultural organizations, researchers, and industry partners interested in testing parcel-level crop stress monitoring in real-world conditions.</p><p>Pilots will help us validate the platform, understand operational needs, and develop Sideris Terra alongside the people who will use it.</p></div><a href={emailHref} className={primaryButton}>Discuss a pilot project <ArrowRight size={16} aria-hidden="true" /></a></div></div></section>
    <section id="team" className="content-section scroll-mt-20"><div className="site-width"><div className="section-intro"><div><h2>Founders</h2></div></div><div className="team-list">{TEAM_MEMBERS.map((member) => <article key={member.name} className="team-member"><img src={member.photoUrl} alt={`${member.name}, ${member.role}`} /><div className="team-details"><div><h3>{member.name}</h3><p className="team-role">{member.role}</p></div><a href={member.linkedinUrl} target="_blank" rel="noreferrer" className="linkedin-mark" aria-label={`${member.name} on LinkedIn`}>in</a><p className="team-bio">{member.bio}</p></div></article>)}</div></div></section>
    <section id="contact" className="contact-section scroll-mt-20"><div className="site-width contact-layout"><div><h2>Contact</h2><p className="section-lede">We would be happy to speak with growers, researchers, agricultural organizations, and technology partners.</p></div><a href={emailHref} className="contact-email"><Mail size={17} aria-hidden="true" />{CONTACT_EMAIL}</a></div></section>
    <footer className="site-footer"><div className="site-width footer-inner"><div><Brand /><p>Parcel-level agricultural intelligence.</p></div><div className="footer-meta"><a href={emailHref}>Email</a><span>ÃƒÆ’Ã¢â‚¬Å¡Ãƒâ€šÃ‚Â© 2026 Sideris Terra</span></div></div></footer>
  </main>;
}